### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by kavienanj** [sainiteshb/NASA-Apod-flutter#11]
Save the fetched data locally, and retrieve them when user is offline.

**Comment by kavienanj** [comment]
Offline support added. Check #12

**Comment by sainiteshb** [comment]
App is having an error, whenever i try to swipe the apod , it showing an error , which gets resolved but its not good for the app look into it. Its returning receiver null.

**Comment by kavienanj** [comment]
Ill check. But the caching works perfectly. I would suggest to close this issue and reopen a new issue mentioning the error.

**Comment by sainiteshb** [comment]
please look into the issue #14
