### ISSUE TITLE
Black bars at bottom and top of screen [iPhone 11]

### ISSUE THREAD

**Issue by jordanmlacalle** [sainiteshb/NASA-Apod-flutter#4]
**Description**
Due to the use of SafeArea around the Scaffold, there are black bars at the bottom and top of the screen. To a user, this may be visually unappealing and would prevent them from seeing their status bar icons.

If the rounded title container that scrolls away is desired, I would suggest placing all content in a CustomScrollView and using a SliverAppBar.

**Comment by sainiteshb** [comment]
Yes thanks for your  suggestion , i will change it.😀
