### ISSUE TITLE
Swipe option to view previous days APOD

### ISSUE THREAD

**Issue by ufrshubham** [sainiteshb/NASA-Apod-flutter#6]
Add swiping feature to move to previous or next days APOD.

**Comment by ufrshubham** [comment]
I tried to do a prototype for this and here are the results. But I am still not happy about it the code design. I'll polish it a little and submit a pull request.

![Proto](https://user-images.githubusercontent.com/33748002/95217052-6744e780-0810-11eb-9ab4-bae38599f69d.gif)

@sainiteshb you can assign this issue to me if you want, so that other know that someone is working on it.

**Comment by sainiteshb** [comment]
Omg thats really a great improvement ! You are really good . REally looking forward for the PR. It looks good if final output should be like only the content moves but not the screen . All the best .

**Comment by sainiteshb** [comment]
Please go ahead , i assign this issue to you

**Comment by ufrshubham** [comment]
You will have to manually assign this issue to me. It is current assigned to no one.
![image](https://user-images.githubusercontent.com/33748002/95301710-986bf900-089e-11eb-8fb1-4d08c9bcbade.png)

**Comment by sainiteshb** [comment]
Did it .
